services:
#  db:
#    container_name: post
#    image: postgres:15.4
#    environment:
#      POSTGRES_USER: whiz
#      POSTGRES_PASSWORD: isaacwhiz
#      PGDATA: /data/full_stack
#    volumes:
#        - db:/data/full_stack
#    ports:
#        - "2001:5432"
#    networks:
#      - db
#    restart: unless-stopped
#
#  isaacwhiz-api:
#   container_name: whiz-api
#   image: isaacwhiz/whiz-api
#   environment:
#     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/full_stack
#   ports:
#     - "8088:8080"
#   networks:
#     - db
#   depends_on:
#     - db
#   restart: unless-stopped
#   command:
#     - --spring.datasource.url=jdbc:postgresql://db:5432/full_stack

  isaacwhiz-react:
    container_name: frontend-react14
    image: isaacwhiz/whiz-react14
    build:
      context: frontend/react
#      args:
#        api_base_url: http://localhost:8088
    ports:
      - "4000:5173"
#    depends_on:
#      - isaacwhiz-api
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
    db:
